[33mWARNING[0m:  No config file found, using default config
app:
  env: dev
  prometheus_dir: /tmp/prometheus
logging:
  level: info
  log_config:
    disable_existing_loggers: false
    formatters:
      default:
        (): ant31box.logutils.DefaultFormatter
        fmt: '%(levelprefix)s %(message)s'
        use_colors: true
    handlers:
      default:
        class: logging.StreamHandler
        formatter: default
        level: INFO
        stream: ext://sys.stdout
    loggers:
      ant31box:
        handlers:
        - default
        level: INFO
        propagate: true
      opticr:
        handlers:
        - default
        level: INFO
        propagate: true
    version: 1
  use_colors: true
name: opticr
ocr:
  default: tesseract
  google_vision:
    service_account_json: service-account.json
  tesseract: {}
sentry:
  dsn: null
  environment: null
  release: null
  traces_sample_rate: null
server:
  cors:
    allow_credentials: false
    allow_headers:
    - '*'
    allow_methods:
    - '*'
    allow_origin_regex: .*
    allow_origins:
    - http://localhost:8080
    - http://localhost:8000
    - http://localhost
  host: 0.0.0.0
  middlewares: []
  middlewares_replace_default: null
  port: 8080
  reload: false
  routers: []
  routers_replace_default: null
  server: opticr.server.server:serve
  token: ''

