name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pip3 install poetry -U
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install
    - name: lint | black codestyle
      run: |
        make black-test

    - name: lint | pylint
      run: |
        make pylint

    - name: lint | pyre-check typing
      run: |
        make pyre-check

    - name: lint | poetry lockfile
      run: |
        make poetry-check

    - name: test | run PyTest
      run: |
        make test
